# Netlify configuration file for Next.js project

[build]
# The directory where Netlify will run the build commands
base = "/"

# The command Netlify should run to build the project
command = "npm run build && npm run export"

# The directory to deploy after building
publish = "dist"

# Environment variables for the build process
[build.environment]
NODE_VERSION = "18"
NEXT_PUBLIC_ENV_VAR = "production"

# Netlify plugin for Next.js to handle SSR, SSG, and static file handling
[[plugins]]
package = "@netlify/plugin-nextjs"

