name: Update database

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
    

jobs:
  Update_json:
    env:
      API_AUTH_TOKEN: ${{ secrets.API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - name: Run all tasks in parallel
        run: |
          zig build run_databaseCompiler > ./database/main.json &
          zig build run_databaseCompiler2 > ./database/programs.json &
          zig build run_repoListCompressor -- web > ./database/web.json &
          zig build run_repoListCompressor -- gui > ./database/gui.json &
          zig build run_repoListCompressor -- games > ./database/games.json &
          zig build run_codeberg > ./database/codebergPrograms.json &
          wait

      - name: Config email
        run: git config --global user.name "Github Actions" && git config --global user.email "<>"
      
      - name: Git add
        run: git add .

      - name: Commit database
        run: git commit -m 'Updated database'

      - name: Push changes
        run: git push
