name: Update database

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  Update_json:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4 
      - name: install zig
        run: brew install zig
      - name: download jsons
        run: |
          wget -O ./a.json "https://api.github.com/search/repositories?q=topic:zig-package&page=1&per_page=100"
          wget -O ./b.json "https://api.github.com/search/repositories?q=topic:zig-package&page=2&per_page=100"
          wget -O ./c.json "https://api.github.com/search/repositories?q=topic:zig-package&page=3&per_page=100"
      - name: Compile zig
        run: zig cc ./scripts/parser.zig
      - name: Run zig
        run: ./a.out > ./database/main.json
      - name: Remove
        run: |
          rm -rf ./a.json
          rm -rf ./b.json
          rm -rf ./c.json
          rm -rf ./a.out
          rm -rf ./a.out.o
      - name: Config email
        run: git config --global user.name "Github Actions" && git config --global user.email "<>"
      - name: Git add
        run: git add .
      - name: Commit images
        run: git commit -m '[CI] Updated database'
      - name: Push changes
        run: git push