name: Update database

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  Update_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      - uses: mlugg/setup-zig@v1
      - name: download jsons
        run: |
          wget -O ./a.json "https://api.github.com/search/repositories?q=topic:zig-package+fork:true&page=1&per_page=100"
          wget -O ./b.json "https://api.github.com/search/repositories?q=topic:zig-package+fork:true&page=2&per_page=100"
          wget -O ./c.json "https://api.github.com/search/repositories?q=topic:zig-package+fork:true&page=3&per_page=100"
          wget -O ./d.json "https://api.github.com/search/repositories?q=topic:zig-package+fork:true&page=4&per_page=100"
      - name: Compile zig
        run: zig build-exe ./scripts/database_compiler.zig
      - name: Run zig
        run: ./database_compiler > ./database/main.json
      - name: Ok run
        run: sh ./scripts/featured.sh
      - name: Run
        run: zig cc -o compressor ./scripts/repo_list_compressor.zig
      - name: adf
        run: ./compressor ./web.json > ./database/web.json
      - name: ksld
        run: ./compressor ./gui.json > ./database/gui.json
      - name: skdj
        run: ./compressor ./games.json > ./database/games.json
      - name: compile AI chat bot compiler
        run: zig cc -o ai_compiler ./chatbot/src/compiler.zig
      - name: Run AI chat bot compiler
        run: ./ai_compiler > ./chatbot/chatbot_compiled.ts
      - name: Remove
        run: |
          rm -rf ./a.json
          rm -rf ./b.json
          rm -rf ./c.json
          rm -rf ./d.json
          rm -rf ./database_compiler
          rm -rf ./database_compiler.o
          rm -rf ./gui.json
          rm -rf ./games.json
          rm -rf ./web.json
          rm -rf ./compressor
          rm -rf ./ai_compiler
      - name: Config email
        run: git config --global user.name "Github Actions" && git config --global user.email "<>"
      - name: Git add
        run: git add .
      - name: Commit images
        run: git commit -m '[CI] Updated database'
      - name: Push changes
        run: git push
