name: Check

on:
  push:
    branches:
      - main


jobs:
  Update_json:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4 
      - name: Install brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: chmod
        run: chmod +x ./scripts/runner.sh
      - name: Runner
        run: ./scripts/runner.sh
      - name: Config email
        run: git config --global user.name "Github Actions" && git config --global user.email "<>"
      - name: Git add
        run: git add .
      - name: Commit images
        run: git commit -m '[CI] Updated images'
      - name: Push changes
        run: git push